### PR TITLE
More explicit From implementations for Scalar

### PR DESCRIPTION
**Pull request by andrewwhitehead**
This appears to fix the compilation issue for anoncreds-v2-rs.

### CODE REVIEW

**Comment by swcurran** [comment]
@mikelodder7 — please take a look.

**Comment by haroldcarr** [comment]
I am still curious as to why the main branch stopped compiling - even though it was fine - and nothing changed.

**Review by mikelodder7 — APPROVED** [review]

**Comment by mikelodder7** [comment]
Not sure why this would fix it per se. Ark must’ve changed something

**Comment by haroldcarr** [comment]
What else needs to happen before this makes it into the `main` branch?

**Pull request merged**
